# Generated by Django 5.2.6 on 2025-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoMestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_arquitetura', models.CharField(max_length=100, unique=True, verbose_name='Código da Arquitetura')),
                ('macroprocesso', models.CharField(max_length=255, verbose_name='Macroprocesso')),
                ('processo', models.CharField(max_length=255, verbose_name='Processo')),
                ('subprocesso', models.CharField(max_length=255, verbose_name='Subprocesso')),
                ('atividade', models.CharField(max_length=255, verbose_name='Atividade')),
            ],
        ),
    ]
