# Generated by Django 5.2.6 on 2025-09-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('mes_ano', models.CharField(max_length=7, verbose_name='Mês/Ano de Referência (MM/YYYY)')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('entrega_esperada', models.TextField(verbose_name='Entrega Esperada da Atividade')),
                ('processo_mestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.processomestre', verbose_name='Identificação do Processo')),
            ],
        ),
    ]
