# Generated by Django 5.2.6 on 2025-09-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_pop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
