# Generated by Django 5.2.6 on 2025-10-09 00:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_controlegastos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Procedimento Operacional Padrão', 'verbose_name_plural': 'Procedimentos Operacionais Padrão'},
        ),
        migrations.AddField(
            model_name='pop',
            name='area_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Área'),
        ),
        migrations.AddField(
            model_name='pop',
            name='area_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Área'),
        ),
        migrations.AddField(
            model_name='pop',
            name='autosave_sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequência de Auto-Save'),
        ),
        migrations.AddField(
            model_name='pop',
            name='codigo_processo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Processo'),
        ),
        migrations.AddField(
            model_name='pop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='pop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='pop',
            name='dispositivos_normativos',
            field=models.TextField(blank=True, null=True, verbose_name='Dispositivos Normativos'),
        ),
        migrations.AddField(
            model_name='pop',
            name='documentos_utilizados',
            field=models.JSONField(default=list, verbose_name='Documentos Utilizados'),
        ),
        migrations.AddField(
            model_name='pop',
            name='etapas',
            field=models.JSONField(default=list, verbose_name='Etapas do Processo'),
        ),
        migrations.AddField(
            model_name='pop',
            name='fluxos_entrada',
            field=models.JSONField(default=list, verbose_name='Fluxos de Entrada'),
        ),
        migrations.AddField(
            model_name='pop',
            name='fluxos_saida',
            field=models.JSONField(default=list, verbose_name='Fluxos de Saída'),
        ),
        migrations.AddField(
            model_name='pop',
            name='integrity_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash de Integridade (SHA256)'),
        ),
        migrations.AddField(
            model_name='pop',
            name='is_completo',
            field=models.BooleanField(default=False, verbose_name='POP Completo'),
        ),
        migrations.AddField(
            model_name='pop',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Excluído (soft delete)'),
        ),
        migrations.AddField(
            model_name='pop',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Atividade'),
        ),
        migrations.AddField(
            model_name='pop',
            name='last_autosave_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Auto-Save'),
        ),
        migrations.AddField(
            model_name='pop',
            name='macroprocesso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Macroprocesso'),
        ),
        migrations.AddField(
            model_name='pop',
            name='nome_processo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Processo'),
        ),
        migrations.AddField(
            model_name='pop',
            name='nome_usuario',
            field=models.CharField(default='admin', max_length=255, verbose_name='Nome do Usuário'),
        ),
        migrations.AddField(
            model_name='pop',
            name='operadores',
            field=models.TextField(blank=True, null=True, verbose_name='Operadores'),
        ),
        migrations.AddField(
            model_name='pop',
            name='pontos_atencao',
            field=models.TextField(blank=True, null=True, verbose_name='Pontos de Atenção'),
        ),
        migrations.AddField(
            model_name='pop',
            name='processo_especifico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Processo Específico'),
        ),
        migrations.AddField(
            model_name='pop',
            name='raw_payload',
            field=models.JSONField(blank=True, help_text='Conteúdo bruto recebido do frontend para reconstrução ou depuração', null=True, verbose_name='Payload Bruto'),
        ),
        migrations.AddField(
            model_name='pop',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Sessão'),
        ),
        migrations.AddField(
            model_name='pop',
            name='sistemas_utilizados',
            field=models.JSONField(default=list, verbose_name='Sistemas Utilizados'),
        ),
        migrations.AddField(
            model_name='pop',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em Edição'), ('review', 'Em Revisão'), ('approved', 'Aprovado'), ('archived', 'Arquivado')], default='draft', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='pop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='pop',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador imutável do POP gerado no momento da criação', verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='entrega_esperada',
            field=models.TextField(blank=True, null=True, verbose_name='Entrega Esperada da Atividade'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='mes_ano',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Mês/Ano de Referência (MM/YYYY)'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='processo_mestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.processomestre', verbose_name='Identificação do Processo'),
        ),
        migrations.CreateModel(
            name='POPChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado em')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Novo Valor')),
                ('diff_text', models.TextField(blank=True, null=True, verbose_name='Diff Textual')),
                ('autosave_sequence', models.PositiveIntegerField(default=0, verbose_name='Sequência de Auto-Save')),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='processos.pop', verbose_name='POP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Alteração de POP',
                'verbose_name_plural': 'Logs de Alteração de POP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POPSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequência')),
                ('versao', models.PositiveIntegerField(verbose_name='Versão do POP no Momento')),
                ('autosave_sequence', models.PositiveIntegerField(default=0, verbose_name='Sequência de Auto-Save no Momento')),
                ('status', models.CharField(max_length=30, verbose_name='Status no Momento')),
                ('integrity_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash de Integridade')),
                ('payload', models.JSONField(verbose_name='Dados Serializados do POP')),
                ('milestone', models.BooleanField(default=False, verbose_name='Marco (Milestone)')),
                ('milestone_label', models.CharField(blank=True, max_length=120, null=True, verbose_name='Rótulo do Marco')),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='processos.pop', verbose_name='POP')),
            ],
            options={
                'verbose_name': 'Snapshot de POP',
                'verbose_name_plural': 'Snapshots de POP',
                'ordering': ['-created_at'],
            },
        ),
    ]
