# Generated by Django 5.2.6 on 2025-10-09 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_alter_pop_options_pop_area_codigo_pop_area_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador imutável do POP gerado no momento da criação', unique=True, verbose_name='UUID'),
        ),
    ]
