# Generated by Django 5.2.6 on 2025-10-13 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_alter_pop_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelenaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Identificador único da sessão (UUID gerado pelo frontend)', max_length=255, unique=True, verbose_name='ID da Sessão')),
                ('produto', models.CharField(default='gerador_pop', help_text='Qual produto: gerador_pop, fluxograma, analise_riscos, etc', max_length=50, verbose_name='Produto Helena')),
                ('estado', models.CharField(default='nome', help_text='Estado da máquina de estados: nome, area, arquitetura, campos, etc', max_length=50, verbose_name='Estado Atual')),
                ('dados', models.JSONField(default=dict, help_text='Estado completo serializado: nome_usuario, sistemas_selecionados, etapas, etc', verbose_name='Dados da Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Atividade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sessão Ativa')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Cliente')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('pop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helena_sessions', to='processos.pop', verbose_name='POP Vinculado')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário autenticado (opcional para sessões anônimas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão Helena',
                'verbose_name_plural': 'Sessões Helena',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_id'], name='processos_h_session_4ca3e8_idx'), models.Index(fields=['is_active', 'updated_at'], name='processos_h_is_acti_b97dca_idx'), models.Index(fields=['user', 'produto'], name='processos_h_user_id_640a54_idx')],
            },
        ),
    ]
