# Generated by Django 5.2.6 on 2025-10-22 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_helenasession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do órgão no SIORG (Sistema de Informações Organizacionais do Governo Federal)', max_length=20, unique=True, verbose_name='Código SIORG')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Órgão')),
                ('sigla', models.CharField(help_text='Ex: AGU, CGU, MEC', max_length=20, verbose_name='Sigla')),
                ('tipo', models.CharField(choices=[('federal', 'Federal'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('autarquia', 'Autarquia'), ('fundacao', 'Fundação'), ('empresa_publica', 'Empresa Pública')], default='federal', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail institucional')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, help_text='Órgãos inativos não podem criar novos dados', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('orgao_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgaos_filhos', to='processos.orgao', verbose_name='Órgão Superior')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador único da sessão', unique=True, verbose_name='ID da Sessão')),
                ('contexto_atual', models.CharField(default='etapas', help_text='Produto Helena ativo (etapas, pop, fluxograma, riscos, etc.)', max_length=50, verbose_name='Contexto Atual')),
                ('estados', models.JSONField(default=dict, help_text="Estado de cada agente: {'etapas': {...}, 'pop': {...}}", verbose_name='Estados dos Agentes')),
                ('agent_versions', models.JSONField(default=dict, help_text="Versão de cada agente usado: {'etapas': '1.0.0', 'pop': '1.2.0'}", verbose_name='Versões dos Agentes')),
                ('api_version', models.CharField(default='2025-10-01', help_text='Versão da API MapaGov usada', max_length=20, verbose_name='Versão da API')),
                ('titulo', models.CharField(blank=True, help_text="Título descritivo da sessão (ex: 'Mapeamento de Compras')", max_length=255, verbose_name='Título')),
                ('tags', models.JSONField(default=list, help_text="Tags para organização: ['urgente', 'licitacao', 'compras']", verbose_name='Tags')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('arquivada', 'Arquivada')], default='ativa', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('orgao', models.ForeignKey(help_text='Órgão ao qual a sessão pertence (multi-tenancy)', on_delete=django.db.models.deletion.PROTECT, related_name='chat_sessions', to='processos.orgao', verbose_name='Órgão')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_uuid', models.UUIDField(db_index=True, help_text='UUID único por request (garante idempotência em retries)', unique=True, verbose_name='Request UUID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente (Helena)'), ('system', 'Sistema')], help_text='Quem enviou a mensagem', max_length=10, verbose_name='Papel')),
                ('content', models.TextField(help_text='Texto da mensagem', verbose_name='Conteúdo')),
                ('contexto', models.CharField(help_text='Produto Helena ativo quando mensagem foi enviada', max_length=50, verbose_name='Contexto')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Dados extras: tokens usados, latência, model usado, etc.', verbose_name='Metadados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(help_text='Redundante com session.user, mas útil para auditoria', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='processos.chatsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['session', 'criado_em'], name='processos_c_session_ddfde7_idx'), models.Index(fields=['req_uuid'], name='processos_c_req_uui_74c287_idx'), models.Index(fields=['user', '-criado_em'], name='processos_c_user_id_0677fe_idx'), models.Index(fields=['contexto', '-criado_em'], name='processos_c_context_68ca4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('req_uuid',), name='unique_request_uuid')],
            },
        ),
        migrations.AddIndex(
            model_name='orgao',
            index=models.Index(fields=['codigo'], name='processos_o_codigo_140dce_idx'),
        ),
        migrations.AddIndex(
            model_name='orgao',
            index=models.Index(fields=['sigla'], name='processos_o_sigla_a276eb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='processos_c_session_1779ce_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['orgao', '-criado_em'], name='processos_c_orgao_i_20f422_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-criado_em'], name='processos_c_user_id_5b3e80_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', '-atualizado_em'], name='processos_c_status_91bc85_idx'),
        ),
    ]
