# Generated by Django 5.2.6 on 2025-10-22 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('processos', '0009_add_rbac_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username (preservado mesmo se user for deletado)', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Criar'), ('read', 'Visualizar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('login', 'Login'), ('logout', 'Logout'), ('permission_denied', 'Permissão Negada'), ('export', 'Exportar'), ('import', 'Importar'), ('generate', 'Gerar')], db_index=True, help_text='Tipo de ação executada', max_length=50)),
                ('resource', models.CharField(db_index=True, help_text='Recurso afetado (ex: processo, chat, usuario)', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID do objeto afetado', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Momento da ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do cliente', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent do navegador', null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição legível da ação')),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Se a ação foi bem-sucedida')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro (se falhou)')),
                ('old_value', models.JSONField(blank=True, help_text='Valor anterior (para UPDATE)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Novo valor (para CREATE/UPDATE)', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadados adicionais (query params, body, etc.)')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duração da operação em milissegundos', null=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'processos_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('unauthorized_access', 'Tentativa de Acesso Não Autorizado'), ('permission_escalation', 'Tentativa de Escalação de Privilégios'), ('suspicious_activity', 'Atividade Suspeita'), ('brute_force', 'Tentativa de Força Bruta'), ('data_leak', 'Tentativa de Vazamento de Dados'), ('sql_injection', 'Tentativa de SQL Injection'), ('xss_attempt', 'Tentativa de XSS')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, default='medium', max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict, help_text='Detalhes técnicos do evento')),
                ('resolved', models.BooleanField(default=False, help_text='Se o evento foi investigado/resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas da investigação')),
            ],
            options={
                'verbose_name': 'Evento de Segurança',
                'verbose_name_plural': 'Eventos de Segurança',
                'db_table': 'processos_security_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='permission',
            new_name='processos_p_recurso_c9a018_idx',
            old_name='processos_p_recurso_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='processos_u_user_id_a74c06_idx',
            old_name='processos_u_user_or_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Tipo do objeto afetado', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='orgao',
            field=models.ForeignKey(blank=True, help_text='Órgão do usuário no momento da ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='processos.orgao'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário que executou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='processos_a_user_id_81fbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource', 'action', 'timestamp'], name='processos_a_resourc_01dd22_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['orgao', 'timestamp'], name='processos_a_orgao_i_026692_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['success', 'timestamp'], name='processos_a_success_d49f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='processos_a_content_938a66_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', 'resolved', 'timestamp'], name='processos_s_severit_c3ba7e_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='processos_s_event_t_02c898_idx'),
        ),
    ]
