# Generated by Django 5.2.6 on 2025-10-30 04:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_add_atividades_sugeridas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesugerida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='contexto_atual',
            field=models.CharField(default='pop', help_text='Produto Helena ativo (pop, etapas, fluxograma, riscos, etc.)', max_length=50, verbose_name='Contexto Atual'),
        ),
        migrations.AlterField(
            model_name='historicoatividade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de execução (0 = primeira)')),
                ('what', models.TextField(help_text='Descrição da ação a ser realizada', verbose_name='O que fazer')),
                ('why', models.TextField(help_text='Justificativa e objetivo da ação', verbose_name='Por que fazer')),
                ('where', models.CharField(help_text="Local ou setor de execução (ex: 'CGRIS', 'Online', 'Sala de reuniões')", max_length=200, verbose_name='Onde executar')),
                ('when_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('when_fim', models.DateField(verbose_name='Data de conclusão prevista')),
                ('when_fim_real', models.DateField(blank=True, null=True, verbose_name='Data de conclusão real')),
                ('who', models.CharField(help_text='Nome do responsável ou equipe', max_length=200, verbose_name='Quem é responsável')),
                ('how', models.TextField(help_text='Metodologia, estratégia ou passos para executar', verbose_name='Como fazer')),
                ('how_much_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo estimado (R$)')),
                ('how_much_real', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo real (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('revisao', 'Em Revisão'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais sobre a ação')),
                ('bloqueadores', models.TextField(blank=True, help_text='Bloqueadores ou impedimentos identificados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('who_user', models.ForeignKey(blank=True, help_text='Usuário responsável (se cadastrado no sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'db_table': 'acoes',
                'ordering': ['plano', 'ordem', 'when_fim'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('atualizacao', 'Atualização de Status'), ('alerta', 'Alerta/Problema'), ('observacao', 'Observação Geral')], default='observacao', max_length=20)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='processos.acao')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário de Ação',
                'verbose_name_plural': 'Comentários de Ações',
                'db_table': 'comentarios_acao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título do plano de ação (ex: 'Mobilização CGRIS - Q1 2026')", max_length=200)),
                ('tipo', models.CharField(choices=[('mobilizacao', 'Mobilização para Mapeamento'), ('riscos', 'Mitigação de Riscos'), ('oportunidades', 'Implementação de Oportunidades'), ('auditoria', 'Preparação para Auditoria'), ('treinamento', 'Treinamento de Equipe'), ('implantacao_sistema', 'Implantação de Sistema'), ('conformidade', 'Adequação de Conformidade'), ('outro', 'Outro')], default='mobilizacao', max_length=50)),
                ('objetivo', models.TextField(help_text='Objetivo geral do plano de ação')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do plano')),
                ('prazo_total_dias', models.IntegerField(help_text='Prazo total em dias', validators=[django.core.validators.MinValueValidator(1)])),
                ('custo_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total estimado em R$', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('roi_esperado', models.TextField(blank=True, help_text="ROI esperado (ex: '45 atividades mapeadas', '120h/mês economizadas')")),
                ('area', models.CharField(blank=True, help_text="Área responsável (ex: 'CGRIS', 'CGCAF')", max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('session_id', models.CharField(blank=True, help_text='ID da sessão de chat que criou este plano', max_length=100)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_acao_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'db_table': 'planos_acao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='acao',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='processos.planoacao'),
        ),
    ]
