# Generated by Django 5.2.6 on 2025-10-30 13:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_alter_atividadesugerida_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título do planejamento (ex: 'PE CGRIS 2025-2027')", max_length=200)),
                ('modelo', models.CharField(choices=[('tradicional', 'Planejamento Estratégico Tradicional'), ('bsc', 'Balanced Scorecard Público'), ('okr', 'Objectives and Key Results (OKR)'), ('swot', 'Análise SWOT/FOFA'), ('cenarios', 'Planejamento por Cenários'), ('5w2h', 'Plano de Ação 5W2H'), ('hoshin', 'Hoshin Kanri')], help_text='Modelo/metodologia utilizada', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição geral do planejamento')),
                ('orgao', models.CharField(blank=True, help_text="Órgão/Entidade (ex: 'INSS', 'Ministério da Economia')", max_length=200)),
                ('unidade', models.CharField(blank=True, help_text="Unidade específica (ex: 'CGRIS', 'DECIPEX')", max_length=200)),
                ('escopo', models.CharField(choices=[('institucional', 'Institucional (órgão completo)'), ('unidade', 'Unidade/Departamento'), ('projeto', 'Projeto/Programa específico'), ('outro', 'Outro')], default='unidade', max_length=100)),
                ('diagnostico', models.JSONField(default=dict, help_text='Respostas do diagnóstico inicial')),
                ('maturidade_organizacao', models.CharField(blank=True, choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], help_text='Nível de maturidade em planejamento estratégico', max_length=20)),
                ('horizonte_temporal', models.CharField(blank=True, choices=[('curto', 'Curto Prazo (até 1 ano)'), ('medio', 'Médio Prazo (1-2 anos)'), ('longo', 'Longo Prazo (3+ anos)')], help_text='Horizonte temporal do planejamento', max_length=20)),
                ('pontuacao_modelos', models.JSONField(default=dict, help_text='Pontuação de cada modelo no diagnóstico')),
                ('modelos_recomendados', models.JSONField(default=list, help_text='Top 3 modelos recomendados')),
                ('estrutura', models.JSONField(default=dict, help_text='Estrutura completa do planejamento (varia por modelo)')),
                ('percentual_conclusao', models.IntegerField(default=0, help_text='Percentual de construção do planejamento (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_inicio_vigencia', models.DateField(blank=True, help_text='Data de início da vigência', null=True)),
                ('data_fim_vigencia', models.DateField(blank=True, help_text='Data de término da vigência', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('diagnostico', 'Em Diagnóstico'), ('construcao', 'Em Construção'), ('revisao', 'Em Revisão'), ('aprovado', 'Aprovado'), ('vigente', 'Vigente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='diagnostico', max_length=20)),
                ('session_id', models.CharField(blank=True, help_text='ID da sessão de chat que criou este planejamento', max_length=100)),
                ('versao', models.IntegerField(default=1, help_text='Versão do planejamento (incrementa a cada revisão)')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para categorização')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('planejamento_anterior', models.ForeignKey(blank=True, help_text='Planejamento anterior (se for uma revisão)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes', to='processos.planejamentoestrategico')),
            ],
            options={
                'verbose_name': 'Planejamento Estratégico',
                'verbose_name_plural': 'Planejamentos Estratégicos',
                'db_table': 'planejamentos_estrategicos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text="Código do indicador (ex: 'IND-001')", max_length=50)),
                ('nome', models.CharField(help_text='Nome do indicador', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do indicador')),
                ('tipo', models.CharField(choices=[('eficiencia', 'Eficiência'), ('eficacia', 'Eficácia'), ('efetividade', 'Efetividade'), ('economicidade', 'Economicidade'), ('excelencia', 'Excelência')], help_text='Tipo do indicador', max_length=20)),
                ('formula', models.TextField(blank=True, help_text='Fórmula de cálculo do indicador')),
                ('unidade_medida', models.CharField(help_text="Unidade de medida (ex: '%', 'dias', 'R$')", max_length=50)),
                ('linha_base', models.DecimalField(blank=True, decimal_places=2, help_text='Valor inicial (linha de base)', max_digits=12, null=True)),
                ('meta', models.DecimalField(decimal_places=2, help_text='Meta a ser alcançada', max_digits=12)),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor atual (último medido)', max_digits=12, null=True)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20)),
                ('responsavel', models.CharField(help_text='Nome do responsável pela coleta', max_length=200)),
                ('fonte_dados', models.TextField(blank=True, help_text='Fonte dos dados para o indicador')),
                ('polaridade_positiva', models.BooleanField(default=True, help_text='True se maior é melhor, False se menor é melhor')),
                ('caminho_estrutura', models.CharField(blank=True, help_text="Caminho JSON no campo estrutura (ex: 'perspectivas.sociedade.objetivos[0]')", max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='processos.planejamentoestrategico')),
            ],
            options={
                'verbose_name': 'Indicador Estratégico',
                'verbose_name_plural': 'Indicadores Estratégicos',
                'db_table': 'indicadores_estrategicos',
                'ordering': ['planejamento', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPlanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('caminho_estrutura', models.CharField(blank=True, help_text="Caminho JSON para comentário específico (ex: 'objetivos[0].indicadores[1]')", max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('sugestao', 'Sugestão'), ('questao', 'Questão'), ('aprovacao', 'Aprovação'), ('ressalva', 'Ressalva'), ('observacao', 'Observação')], default='observacao', max_length=20)),
                ('resolvido', models.BooleanField(default=False, help_text='Comentário foi resolvido/endereçado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='processos.planejamentoestrategico')),
            ],
            options={
                'verbose_name': 'Comentário de Planejamento',
                'verbose_name_plural': 'Comentários de Planejamento',
                'db_table': 'comentarios_planejamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MedicaoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data de referência da medição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor medido', max_digits=12)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a medição')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='processos.indicadorestrategico')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medição de Indicador',
                'verbose_name_plural': 'Medições de Indicadores',
                'db_table': 'medicoes_indicadores',
                'ordering': ['-data_referencia'],
                'unique_together': {('indicador', 'data_referencia')},
            },
        ),
        migrations.AddIndex(
            model_name='planejamentoestrategico',
            index=models.Index(fields=['modelo', 'status'], name='planejament_modelo_e02afb_idx'),
        ),
        migrations.AddIndex(
            model_name='planejamentoestrategico',
            index=models.Index(fields=['session_id'], name='planejament_session_4be675_idx'),
        ),
        migrations.AddIndex(
            model_name='planejamentoestrategico',
            index=models.Index(fields=['orgao', 'unidade'], name='planejament_orgao_46cc59_idx'),
        ),
    ]
