# Generated by Django 5.2.6 on 2026-01-30 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_planejamentoestrategico_indicadorestrategico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseRiscos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orgao_id', models.UUIDField(db_index=True)),
                ('tipo_origem', models.CharField(choices=[('POP', 'POP'), ('PROJETO', 'Projeto')], max_length=20)),
                ('origem_id', models.UUIDField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'RASCUNHO'), ('EM_ANALISE', 'EM_ANALISE'), ('FINALIZADA', 'FINALIZADA')], default='RASCUNHO', max_length=20)),
                ('etapa_atual', models.PositiveSmallIntegerField(default=1)),
                ('questoes_respondidas', models.JSONField(blank=True, default=dict)),
                ('area_decipex', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_riscos_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analise de Riscos',
                'verbose_name_plural': 'Analises de Riscos',
                'db_table': 'processos_analise_riscos',
            },
        ),
        migrations.CreateModel(
            name='AnaliseSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao', models.PositiveIntegerField()),
                ('dados_completos', models.JSONField()),
                ('motivo_snapshot', models.CharField(choices=[('AUTO_ETAPA', 'Mudanca de etapa'), ('FINALIZACAO', 'Finalizacao da analise'), ('EDICAO_RISCO', 'Edicao de risco'), ('MANUAL', 'Snapshot manual')], max_length=30)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='processos.analiseriscos')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de Analise',
                'verbose_name_plural': 'Snapshots de Analises',
                'db_table': 'processos_analise_snapshot',
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='RiscoIdentificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orgao_id', models.UUIDField(db_index=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('OPERACIONAL', 'OPERACIONAL'), ('FINANCEIRO', 'FINANCEIRO'), ('LEGAL', 'LEGAL'), ('REPUTACIONAL', 'REPUTACIONAL'), ('TECNOLOGICO', 'TECNOLOGICO'), ('IMPACTO_DESIGUAL', 'IMPACTO_DESIGUAL')], max_length=30)),
                ('probabilidade', models.PositiveSmallIntegerField()),
                ('impacto', models.PositiveSmallIntegerField()),
                ('score_risco', models.PositiveSmallIntegerField(editable=False)),
                ('nivel_risco', models.CharField(choices=[('BAIXO', 'BAIXO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], editable=False, max_length=20)),
                ('fonte_sugestao', models.CharField(choices=[('USUARIO', 'Usuario'), ('HELENA_RAG', 'Helena RAG')], default='USUARIO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='processos.analiseriscos')),
            ],
            options={
                'verbose_name': 'Risco Identificado',
                'verbose_name_plural': 'Riscos Identificados',
                'db_table': 'processos_risco_identificado',
            },
        ),
        migrations.CreateModel(
            name='RespostaRisco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orgao_id', models.UUIDField(db_index=True)),
                ('estrategia', models.CharField(choices=[('MITIGAR', 'MITIGAR'), ('EVITAR', 'EVITAR'), ('COMPARTILHAR', 'COMPARTILHAR'), ('ACEITAR', 'ACEITAR'), ('RESGUARDAR', 'RESGUARDAR')], max_length=20)),
                ('descricao_acao', models.TextField()),
                ('responsavel_nome', models.CharField(max_length=255)),
                ('responsavel_area', models.CharField(max_length=100)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='processos.riscoidentificado')),
            ],
            options={
                'verbose_name': 'Resposta ao Risco',
                'verbose_name_plural': 'Respostas aos Riscos',
                'db_table': 'processos_resposta_risco',
            },
        ),
        migrations.AddIndex(
            model_name='analiseriscos',
            index=models.Index(fields=['orgao_id', 'status'], name='processos_a_orgao_i_0cbe12_idx'),
        ),
        migrations.AddIndex(
            model_name='analiseriscos',
            index=models.Index(fields=['origem_id'], name='processos_a_origem__1838b7_idx'),
        ),
        migrations.AddIndex(
            model_name='analisesnapshot',
            index=models.Index(fields=['analise', '-versao'], name='processos_a_analise_16cb06_idx'),
        ),
        migrations.AddIndex(
            model_name='riscoidentificado',
            index=models.Index(fields=['orgao_id'], name='processos_r_orgao_i_3f5136_idx'),
        ),
        migrations.AddIndex(
            model_name='riscoidentificado',
            index=models.Index(fields=['analise', 'ativo'], name='processos_r_analise_3b7be6_idx'),
        ),
        migrations.AddIndex(
            model_name='respostarisco',
            index=models.Index(fields=['orgao_id'], name='processos_r_orgao_i_f6d25e_idx'),
        ),
    ]
