# Generated by Django 5.2.6 on 2026-01-30 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0016_analise_riscos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseriscos',
            name='contexto_estruturado',
            field=models.JSONField(blank=True, default=dict, help_text='Bloco A (identificacao) + Bloco B (contexto operacional)'),
        ),
        migrations.AddField(
            model_name='analiseriscos',
            name='modo_entrada',
            field=models.CharField(choices=[('QUESTIONARIO', 'QUESTIONARIO'), ('PDF', 'PDF'), ('ID', 'ID')], default='QUESTIONARIO', max_length=20),
        ),
        migrations.AddField(
            model_name='analiseriscos',
            name='respostas_blocos',
            field=models.JSONField(blank=True, default=dict, help_text='Respostas dos 6 blocos de identificacao de riscos'),
        ),
        migrations.AddField(
            model_name='analiseriscos',
            name='texto_extraido',
            field=models.TextField(blank=True, help_text='Texto extraido do PDF para analise'),
        ),
        migrations.AddField(
            model_name='riscoidentificado',
            name='bloco_origem',
            field=models.CharField(blank=True, help_text='Bloco que originou o risco (ex: BLOCO_1)', max_length=20),
        ),
        migrations.AddField(
            model_name='riscoidentificado',
            name='grau_confianca',
            field=models.CharField(blank=True, choices=[('BAIXO', 'BAIXO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO')], help_text='Grau de confianca da inferencia', max_length=10),
        ),
        migrations.AddField(
            model_name='riscoidentificado',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Justificativa rastreavel da inferencia'),
        ),
        migrations.AddField(
            model_name='riscoidentificado',
            name='perguntas_acionadoras',
            field=models.JSONField(blank=True, default=list, help_text="Lista de perguntas que acionaram a regra (ex: ['Q1', 'Q2'])"),
        ),
        migrations.AddField(
            model_name='riscoidentificado',
            name='regra_aplicada',
            field=models.CharField(blank=True, help_text='Identificador da regra de inferencia aplicada', max_length=100),
        ),
        migrations.AlterField(
            model_name='analiseriscos',
            name='etapa_atual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analiseriscos',
            name='origem_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analiseriscos',
            name='tipo_origem',
            field=models.CharField(choices=[('PROJETO', 'PROJETO'), ('PROCESSO', 'PROCESSO'), ('POP', 'POP'), ('POLITICA', 'POLITICA'), ('NORMA', 'NORMA'), ('PLANO', 'PLANO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analisesnapshot',
            name='motivo_snapshot',
            field=models.CharField(choices=[('AUTO_ETAPA', 'Mudanca de etapa'), ('FINALIZACAO', 'Finalizacao da analise'), ('EDICAO_RISCO', 'Edicao de risco'), ('EDICAO_CONTEXTO', 'Edicao de contexto'), ('MANUAL', 'Snapshot manual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='fonte_sugestao',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('HELENA_INFERENCIA', 'Helena Inferencia')], default='USUARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='impacto',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='nivel_risco',
            field=models.CharField(choices=[('BAIXO', 'BAIXO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], default='MEDIO', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='probabilidade',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='score_risco',
            field=models.PositiveSmallIntegerField(default=9, editable=False),
        ),
        migrations.AddIndex(
            model_name='analiseriscos',
            index=models.Index(fields=['modo_entrada'], name='processos_a_modo_en_8efcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='riscoidentificado',
            index=models.Index(fields=['bloco_origem'], name='processos_r_bloco_o_ba3beb_idx'),
        ),
    ]
