# Generated by Django 5.2.6 on 2026-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0018_remove_resguardar_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riscoidentificado',
            name='impacto',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='nivel_risco',
            field=models.CharField(blank=True, choices=[('BAIXO', 'BAIXO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO'), ('CRITICO', 'CRITICO')], default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='probabilidade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riscoidentificado',
            name='score_risco',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
