# Generated by Django 5.2.6 on 2026-02-08 21:05

from django.conf import settings
from django.db import migrations, models


def deduplicar_caps(apps, schema_editor):
    """
    Soft-delete duplicatas de codigo_processo, mantendo apenas o mais recente.
    Necessario para aplicar UniqueConstraint sem violacao.
    """
    POP = apps.get_model('processos', 'POP')
    from django.db.models import Count, Max

    dupes = (
        POP.objects.filter(is_deleted=False)
        .exclude(codigo_processo__isnull=True)
        .exclude(codigo_processo='')
        .values('codigo_processo')
        .annotate(cnt=Count('id'), max_id=Max('id'))
        .filter(cnt__gt=1)
    )

    total = 0
    for d in dupes:
        cap = d['codigo_processo']
        manter_id = d['max_id']
        removidos = POP.objects.filter(
            codigo_processo=cap, is_deleted=False
        ).exclude(id=manter_id).update(is_deleted=True)
        total += removidos

    if total:
        print(f"\n  [0020] Soft-deleted {total} POP(s) duplicados por codigo_processo")


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_remove_pi_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicar_caps, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pop',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('is_deleted', False),
                    models.Q(('codigo_processo', None), _negated=True),
                    models.Q(('codigo_processo', ''), _negated=True),
                ),
                fields=('codigo_processo',),
                name='unique_cap_ativo',
            ),
        ),
    ]
