# Generated by Django 5.2.6 on 2026-02-10 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0021_popdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nome_curto', models.CharField(max_length=100, verbose_name='Nome Curto')),
                ('slug', models.SlugField(help_text='URL-safe: cgben, digep-ro, etc.', max_length=30, unique=True, verbose_name='Slug')),
                ('prefixo', models.CharField(max_length=10, verbose_name='Prefixo numérico')),
                ('ordem', models.FloatField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('tem_subareas', models.BooleanField(default=False, verbose_name='Tem subáreas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Área Organizacional',
                'verbose_name_plural': 'Áreas Organizacionais',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PopVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(verbose_name='Número da versão')),
                ('payload', models.JSONField(verbose_name='Dados completos congelados')),
                ('integrity_hash', models.CharField(max_length=64, verbose_name='Hash SHA256')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado em')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo da publicação')),
                ('is_current', models.BooleanField(default=True, verbose_name='Versão corrente?')),
            ],
            options={
                'verbose_name': 'Versão Publicada de POP',
                'verbose_name_plural': 'Versões Publicadas de POP',
                'ordering': ['-versao'],
            },
        ),
        migrations.RenameIndex(
            model_name='popdraft',
            new_name='processos_p_session_530c3b_idx',
            old_name='processos_p_session_idx',
        ),
        migrations.RenameIndex(
            model_name='popdraft',
            new_name='processos_p_user_id_71671b_idx',
            old_name='processos_p_user_up_idx',
        ),
        migrations.AlterField(
            model_name='pop',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='processos.area', verbose_name='Área Pai'),
        ),
        migrations.AddField(
            model_name='pop',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pops', to='processos.area', verbose_name='Área Organizacional'),
        ),
        migrations.AddField(
            model_name='popversion',
            name='pop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='processos.pop', verbose_name='POP'),
        ),
        migrations.AddField(
            model_name='popversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por'),
        ),
        migrations.AddConstraint(
            model_name='popversion',
            constraint=models.UniqueConstraint(fields=('pop', 'versao'), name='unique_pop_version'),
        ),
    ]
