# Generated by Django 5.2.6 on 2026-02-10 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_access_approver_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='ACCESS_APPROVER')


def remove_access_approver_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='ACCESS_APPROVER').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_populate_areas'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('mgi', 'MGI (gestao.gov.br)'), ('externo', 'Externo')], default='externo', max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('access_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='processos.area')),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='processos.orgao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='AccessApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approve', 'Aprovado'), ('reject', 'Rejeitado')], max_length=10)),
                ('justificativa', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='processos.userprofile')),
            ],
            options={
                'verbose_name': 'Aprovação de Acesso',
                'verbose_name_plural': 'Aprovações de Acesso',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['access_status'], name='processos_u_access__66dfef_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['profile_type', 'access_status'], name='processos_u_profile_de8d31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accessapproval',
            unique_together={('user_profile', 'admin')},
        ),
        migrations.RunPython(
            create_access_approver_group,
            remove_access_approver_group,
        ),
    ]
