# Generated by Django 5.2.6 on 2026-02-16 20:33

from django.db import migrations, models


def promote_superusers(apps, schema_editor):
    """Promove superusers existentes para role='admin'."""
    UserProfile = apps.get_model('processos', 'UserProfile')
    updated = UserProfile.objects.filter(user__is_superuser=True).update(role='admin')
    if updated:
        print(f'  [data] {updated} superuser(s) promovido(s) para role=admin')


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0027_add_cp_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('operator', 'Operador'), ('area_manager', 'Gestor de Area'), ('general_manager', 'Gestor Geral'), ('admin', 'Administrador')], db_index=True, default='operator', max_length=20),
        ),
        migrations.RunPython(promote_superusers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='analiseriscos',
            name='respostas_blocos',
            field=models.JSONField(blank=True, default=dict, help_text='Respostas dos 7 blocos de identificacao de riscos'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criar'), ('read', 'Visualizar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('login', 'Login'), ('logout', 'Logout'), ('permission_denied', 'Permissão Negada'), ('export', 'Exportar'), ('import', 'Importar'), ('generate', 'Gerar'), ('register', 'Registro'), ('email_verify', 'Verificação de E-mail'), ('access_request', 'Solicitação de Acesso'), ('access_approve', 'Aprovação de Acesso'), ('access_reject', 'Rejeição de Acesso'), ('password_reset', 'Reset de Senha')], db_index=True, help_text='Tipo de ação executada', max_length=50),
        ),
        migrations.AlterField(
            model_name='controleindicesproduto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
