# Generated by Django 5.2.6 on 2026-02-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0028_add_role_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_decipex',
            field=models.BooleanField(default=False, verbose_name='Pertence a Decipex'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setor_trabalho',
            field=models.CharField(blank=True, help_text='Informado por usuarios nao-Decipex no cadastro.', max_length=255, verbose_name='Setor de trabalho'),
        ),
    ]
