# Generated by Django 5.2.6 on 2026-03-03 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0029_add_setor_trabalho_is_decipex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='review_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas de revisão / motivo de rejeição'),
        ),
        migrations.AddField(
            model_name='pop',
            name='review_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Snapshot no momento da submissão'),
        ),
        migrations.AddField(
            model_name='pop',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pops_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Último revisor'),
        ),
        migrations.AddField(
            model_name='pop',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pops_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Submetido por'),
        ),
        migrations.AddField(
            model_name='pop',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submetido para revisão em'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em Revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
